<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAk8OfhV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAk8OfhV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAk8OfhV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAk8OfhV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAk8OfhV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ak8OfhV',
    'container.build_id' => '31de0c61',
    'container.build_time' => 1551900495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAk8OfhV');
